# site settings
title: Gringos to Go
subtitle: the journey of a lifetime
email: gringostogos@gmail.com
description: Gringos to Go
baseurl: "/" # the subpath of your site, e.g. /blog
url: "www.gringostogo.de" # the base hostname & protocol for your site
author: Manuel Anrig
street_address: 
city: Sargans
state: SG
zip_code: 7320
country: Switzerland
phone:

# social settings
500px_url:
facebook_url: https://www.facebook.com/gringostogo
github_url:
gitlab_url: 
googleplus_url:
instagram_url: https://www.instagram.com/gringostogo
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
